"""Tests for voice_audio: transcode, VAD, SNR, stage split.

Fixtures are committed under tests/voice/fixtures/ and are *synthetic* —
they are tones/noise generated by scripts/make_voice_fixtures.py, not real
human voice. Their job is to give each extractor a deterministic non-zero
input so the structural assertions hold.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from app.services import voice_audio


FIXTURES = Path(__file__).parent / "fixtures"


def _load(name: str):
    return voice_audio.load_wav((FIXTURES / name).read_bytes())


# ---------------------------------------------------------------------------
# load_wav
# ---------------------------------------------------------------------------


def test_load_wav_returns_float32_mono_at_16k():
    audio, sr = _load("clean_voice_10s.wav")
    assert sr == 16000
    assert audio.dtype == np.float32
    assert audio.ndim == 1


# ---------------------------------------------------------------------------
# transcode_to_wav
# ---------------------------------------------------------------------------


def test_transcode_passes_through_wav_input():
    """When input is already WAV, both ffmpeg and the soundfile fallback
    should produce a 16k mono PCM WAV."""
    raw = (FIXTURES / "clean_voice_10s.wav").read_bytes()
    out = voice_audio.transcode_to_wav(raw)
    audio, sr = voice_audio.load_wav(out)
    assert sr == 16000
    assert audio.ndim == 1
    # Duration should be ~10s (allow ~0.1s slack for ffmpeg framing)
    assert 9.5 <= audio.size / sr <= 10.5


@pytest.mark.skipif(
    not voice_audio.ffmpeg_available(),
    reason="ffmpeg not on PATH (winget install Gyan.FFmpeg)",
)
def test_transcode_handles_pure_silence_input():
    """ffmpeg path: even pure silence WAV transcodes successfully."""
    raw = (FIXTURES / "silence_5s.wav").read_bytes()
    out = voice_audio.transcode_to_wav(raw)
    audio, sr = voice_audio.load_wav(out)
    assert sr == 16000
    assert audio.size > 0


def test_transcode_decodes_browser_style_webm_opus_via_pyav():
    """Regression: browser uploads are WebM/Opus; libsndfile cannot decode
    those, and many machines have no system ffmpeg. The transcoder must
    fall back to PyAV's bundled libav so the worker pipeline still works.

    Without this, /api/voice/v2/upload accepts the file (202) but the
    background task crashes and the recording silently fails — the
    nurse dashboard never updates."""
    import io
    import av
    import numpy as np

    # Synthesise a 1.5 s 440 Hz tone, encode it as WebM/Opus exactly the
    # way Chrome's MediaRecorder would.
    sr = 48000
    t = np.arange(int(1.5 * sr)) / sr
    audio = (0.3 * np.sin(2 * np.pi * 440 * t)).astype(np.float32)
    buf = io.BytesIO()
    out = av.open(buf, mode="w", format="webm")
    stream = out.add_stream("libopus", rate=sr)
    stream.layout = "mono"
    frame = av.AudioFrame.from_ndarray(audio[None, :], format="flt", layout="mono")
    frame.rate = sr
    for packet in stream.encode(frame):
        out.mux(packet)
    for packet in stream.encode(None):
        out.mux(packet)
    out.close()
    webm_bytes = buf.getvalue()
    assert len(webm_bytes) > 0

    wav_bytes = voice_audio.transcode_to_wav(webm_bytes)
    decoded, decoded_sr = voice_audio.load_wav(wav_bytes)
    assert decoded_sr == 16000
    assert decoded.dtype == np.float32
    # Duration ~1.5s, allow ~50ms slack for codec framing
    assert 1.4 <= decoded.size / decoded_sr <= 1.6


# ---------------------------------------------------------------------------
# vad_segments
# ---------------------------------------------------------------------------


def test_vad_returns_empty_for_silence():
    audio, sr = _load("silence_5s.wav")
    assert voice_audio.vad_segments(audio, sr) == []


def test_vad_finds_voiced_segments_in_clean_voice():
    audio, sr = _load("clean_voice_10s.wav")
    segs = voice_audio.vad_segments(audio, sr)
    # Synthetic tone passes Silero's energy gate; we just need >= 1 segment
    assert len(segs) >= 1
    # Segments must be in [0, duration] and non-decreasing
    duration = audio.size / sr
    for s, e in segs:
        assert 0 <= s < e <= duration + 0.05


def test_vad_handles_empty_array():
    assert voice_audio.vad_segments(np.zeros(0, dtype=np.float32), 16000) == []


# ---------------------------------------------------------------------------
# compute_snr_db
# ---------------------------------------------------------------------------


def test_snr_high_for_clean_voice_with_explicit_voiced_segments():
    """SNR math test: when we hand it the voiced regions ourselves the
    20*log10(rms_voiced/rms_silence) calculation should be well above 6 dB.

    (Silero VAD is trained on real speech and doesn't reliably segment our
    synthetic harmonic tones, so we bypass it here to test the math.)"""
    audio, sr = _load("clean_voice_10s.wav")
    # The fixture inserts silence pauses at [2.0, 2.5] and [6.0, 6.5];
    # voiced regions are everything else.
    voiced = [(0.0, 2.0), (2.5, 6.0), (6.5, 10.0)]
    snr = voice_audio.compute_snr_db(audio, sr, voiced=voiced)
    assert snr > 10.0, f"expected SNR >> 6 dB for clean voice fixture, got {snr}"


def test_snr_low_for_pure_noise():
    audio, sr = _load("noisy_5s.wav")
    snr = voice_audio.compute_snr_db(audio, sr)
    # Pure white noise has no clear voiced/silence split — SNR should be
    # at or below the low_snr threshold.
    assert snr < 6.0, f"expected SNR < 6 dB for pure noise, got {snr}"


def test_snr_negative_for_silence():
    audio, sr = _load("silence_5s.wav")
    snr = voice_audio.compute_snr_db(audio, sr)
    # No voiced content -> sentinel at the floor (-60 dB)
    assert snr <= 0.0


# ---------------------------------------------------------------------------
# split_stages
# ---------------------------------------------------------------------------


def _full_offsets():
    return {
        "sustained_a": [0.0, 6.0],
        "ddk": [6.0, 11.0],
        "reading": [11.0, 18.0],
        "open_prompt": [18.0, 30.0],
    }


def test_split_stages_returns_four_arrays_with_correct_sizes():
    sr = 16000
    audio = np.zeros(int(30 * sr), dtype=np.float32)
    out = voice_audio.split_stages(audio, sr, _full_offsets())
    assert set(out.keys()) == set(_full_offsets().keys())
    assert out["sustained_a"].size == 6 * sr
    assert out["ddk"].size == 5 * sr
    assert out["reading"].size == 7 * sr
    assert out["open_prompt"].size == 12 * sr


def test_split_stages_missing_required_stage_raises():
    sr = 16000
    audio = np.zeros(int(30 * sr), dtype=np.float32)
    bad = {"sustained_a": [0.0, 6.0], "ddk": [6.0, 11.0]}  # missing 2 stages
    with pytest.raises(voice_audio.MissingStageError):
        voice_audio.split_stages(audio, sr, bad)


def test_split_stages_decreasing_range_raises():
    sr = 16000
    audio = np.zeros(int(30 * sr), dtype=np.float32)
    bad = dict(_full_offsets(), sustained_a=[5.0, 1.0])
    with pytest.raises(voice_audio.InvalidStageOffsetError):
        voice_audio.split_stages(audio, sr, bad)


def test_split_stages_out_of_bounds_clamps_end():
    """end past audio length is clamped (allows ~0.5s grace) but start
    well past duration raises."""
    sr = 16000
    audio = np.zeros(int(20 * sr), dtype=np.float32)
    # open_prompt extends past audio length; we accept the clamp.
    offsets = dict(_full_offsets(), open_prompt=[18.0, 30.0])
    out = voice_audio.split_stages(audio, sr, offsets)
    assert out["open_prompt"].size <= 12 * sr  # clamped
    # Start past the end raises explicitly
    bad = dict(_full_offsets(), reading=[100.0, 120.0])
    with pytest.raises(voice_audio.InvalidStageOffsetError):
        voice_audio.split_stages(audio, sr, bad)
